---
default:
  # general behavior ---------------------------------------------------------------------------------------------------
  do_search: true
  get_all_elements: false
  keep_all_elements: false
  n_cores: 12
  max_bundles: 10 # limit value for testing/debugging, else use .inf
  max_bundle_size: 100 # set max. bundle size using _count parameter in FHIR search, e.g. 1000
  
  save_to_disc: false #TODO: not yet implemented, has to be false for now.
  log_dir: 'logs' # directory for logfiles
  tmp_dir: 'tmp' # directory to store downloaded bundles / intermediate results, if applicable
  
  # server settings ----------------------------------------------------------------------------------------------------
#  hospital_name: 'UKDD'
#  hospital_zip: '01307'

  filebase: 'data/FHIR_patient_examples' # if !do_search, XML FHIR resources/bundles will be read from this folder
  serverbase: 'https://hapi.fhir.org/baseR4'
  username: null
  password: null
  token: null
  http_proxy: null
  https_proxy: null
  no_proxy: null # put fhir server adress here, if you need to bypass the proxy for accessing it locally
  ssl_verify_peer: false
  
  # server coding customization ----------------------------------------------------------------------------------------
  # set custom reference prefixes if they can't be detected automatically
  ref_prefixes:
    encounter:
      subject.reference: null
      diagnosis.condition.reference: null
  
  sep: ":::" # could probably be hardcoded in R, doesn't need to be customized by a site
  brackets: ["[", "]"] # same

