# Configuration of FHIR search parameters and resource element selection.
# - FHIR search parameters
# - FHIR elements to include in FHIR search

---
default:
  # FHIR search parameters -------------------------------------------------------------------------

  parameters:
    # FHIR searches will be performed sequentially as they appear in this 'parameters' section.
    # type: list of strings of the form SearchParameter=SearchValue

    encounter:
      # admission date greater or equal to 2016-01-01
      - "date=ge2016-01-01"
      # admission date less or equal to 2022-03-31
      - "date=le2022-03-31"
      # birthdate greater or equal to 1998-01-01 (upper limit for underage patients at the begin
      # of the study interval)
      - "patient.birthdate=ge1998"
      # patients with a german address
      - "patient.address-country=d,ger"

      # If the FHIR server has implemented a custom SearchParameter for ServiceType, uncomment the
      # servicetype parameter below. This will improve performance, reducing load on the FHIR
      # server by only querying encounters with contact to the specified departments (example
      # implementation can be found at https://fshschool.org/FSHOnline/#/share/3KrPtLc)
      #- "servicetype=https://www.medizininformatik-initiative.de/fhir/core/modul-fall/CodeSystem/Fachabteilungsschluessel|1000,3000"

    # At the current state, further search parameters are generated only within the script.
    patient: null
    condition: null
    procedure: null

  # FHIR elements to include in FHIR searches ------------------------------------------------------

  elements:
  # This section defines per resource a list of FHIR elements (in XPath format) to control which
  # elements of the respective FHIR resource are a) downloaded for the respective FHIR search
  # and/or b) kept during processing.
  # a) to limit downloads to the elements specified below (default setting), set 'get_all_elements'
  #    in 'fhir_cfg.yml' to false.
  # b) to constrict processed data to the elements specified below (default setting), set
  #    'keep_all_elements' in 'fhir_cfg.yml' to false.
  # See respective settings in 'fhir_cfg.yml' for additional information. type: list of strings

    patient:
      ## to extract
      - "address/postalCode"
      - "birthDate"
      - "deceasedBoolean"
      - "deceasedDateTime"
      - "gender"
      - "id"
      - "identifier/assigner/identifier/value"
      - "identifier/value"

      ## for QC only, to be discarded before export
      - "address/country"
      #- "address/type" # "both"
      #- "identifier/assigner/identifier/system"
      #- "identifier/assigner/identifier/type/coding/code"
      #- "identifier/assigner/identifier/type/coding/system"
      - "identifier/system"
      #- "identifier/type/coding/code"
      #- "identifier/type/coding/system"
      #- "identifier/use"
      - "meta/lastUpdated"
      - "meta/profile"
      #- "meta/security/code"
      #- "meta/security/display"
      #- "meta/security/system"
      - "meta/source"
      #- "meta/versionId"
      #- "name/extension"
      #- "name/extension/valueCoding/code"
      #- "name/extension/valueCoding/display"
      #- "name/extension/valueCoding/system"

    encounter:
      ## to extract
      - "class/display"
      - "hospitalization/admitSource/coding/code"
      - "hospitalization/admitSource/coding/display"
      - "hospitalization/admitSource/text"
      - "hospitalization/dischargeDisposition/coding/code"
      - "hospitalization/dischargeDisposition/coding/display"
      - "hospitalization/dischargeDisposition/text"
      - "id"
      - "identifier/value"
      - "period/end"
      - "period/start"
      - "reasonCode/coding/code"
      - "reasonCode/coding/display"
      - "serviceType/coding/code"
      - "serviceType/coding/display"
      - "serviceType/text"
      - "status"
      - "subject/reference"
      - "type/coding/code"
      - "type/coding/display"
      - "type/text"

      ## mappings & info about conditions
      #- "diagnosis/condition/identifier/system"
      #- "diagnosis/condition/identifier/value"
      - "diagnosis/condition/reference"
      - "diagnosis/rank"
      - "diagnosis/use/coding/code"
      - "diagnosis/use/coding/display"
      #- "diagnosis/use/coding/system"

      ## locations, might need to be unpacked
      #- "location/location/identifier/system"
      - "location/location/identifier/value"
      - "location/period/end"
      - "location/period/start"
      - "location/physicalType/coding/code"
      - "location/physicalType/coding/display"
      - "location/physicalType/coding/system"
      - "location/status"
      - "partOf/reference"

      ## for QC only, discarded before export
      #- "class/code"
      - "class/system"
      - "hospitalization/admitSource/coding/system"
      - "hospitalization/dischargeDisposition/coding/system"
      #- "identifier/assigner/identifier/system"
      #- "identifier/assigner/identifier/value"
      - "identifier/system"
      #- "identifier/type/coding/code"
      #- "identifier/type/coding/system"
      #- "identifier/use"
      - "meta/lastUpdated"
      #- "meta/profile"
      #- "meta/security/code"
      #- "meta/security/display"
      #- "meta/security/system"
      - "meta/source"
      #- "meta/versionId"
      - "reasonCode/coding/system"
      #- "serviceProvider/identifier/system"
      - "serviceProvider/identifier/value"
      - "serviceType/coding/system"
      #- "subject/identifier/system"
      #- "subject/identifier/value"
      #- "type/coding/system"

    condition:
      ## to extract
      - "code/coding/code"
      - "code/coding/display"
      - "code/coding/system"
      - "code/coding/version"
      - "code/text"
      - "encounter/reference"
      - "id"
      - "onsetDateTime"
      - "onsetPeriod/end"
      - "onsetPeriod/start"
      - "recordedDate"
      - "subject/reference"
      - "verificationStatus/coding/code"
      - "verificationStatus/coding/display"
      - "verificationStatus/coding/system"
      - "verificationStatus/text"

      ## bodySite, if not handled as code.coding:icd10-gm.extension Seitenlokalisation
      - "bodySite/coding/code"
      - "bodySite/coding/display"
      - "bodySite/coding/system"
      - "bodySite/text"

      ## Extensions - need extra handling
      ##  (Seitenlokalisation, Diagnosesicherheit, Mehrfachkodierungen,
      ##  Neben-/2.-Diagnosen "condition-related")
      - "code/coding/extension"
      - "code/coding/extension/valueCoding/code"
      - "code/coding/extension/valueCoding/display"
      - "code/coding/extension/valueCoding/system"
      - "extension"
      - "extension/valueReference/reference"

      ## for QC only, discarded before export
      #- "identifier/system"
      #- "identifier/use"
      - "identifier/value"
      - "meta/lastUpdated"
      - "meta/profile"
      #- "meta/security/code"
      #- "meta/security/display"
      #- "meta/security/system"
      - "meta/source"
      #- "meta/versionId"

